# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubReposApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubReposApp
  pod 'Alamofire', '~> 3.0'

  target 'GithubReposAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GithubReposApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubReposApp-tvOS

  target 'GithubReposApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
  

end
